CREATE TABLE production_orders (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  formulation_version_id VARCHAR(191) NOT NULL,
  status ENUM('borrador','planeada','liberada','en_proceso','pausada','terminada','cancelada') NOT NULL DEFAULT 'borrador',
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  target_lot_code VARCHAR(191) NOT NULL,
  planned_quantity DOUBLE NOT NULL,
  planned_unit VARCHAR(191) NOT NULL DEFAULT 'g',
  expected_yield DOUBLE NOT NULL,
  responsible_user_id VARCHAR(191) NULL,
  operator_user_id VARCHAR(191) NOT NULL,
  planned_start_at DATETIME(3) NULL,
  planned_end_at DATETIME(3) NULL,
  started_at DATETIME(3) NULL,
  finished_at DATETIME(3) NULL,
  actual_yield DOUBLE NULL,
  yield_difference DOUBLE NULL,
  waste_total DOUBLE NOT NULL DEFAULT 0,
  expected_cost DOUBLE NULL,
  notes TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY production_orders_org_code_unique (organization_id, permanent_code),
  KEY production_orders_organization_id_idx (organization_id),
  KEY production_orders_formulation_version_id_idx (formulation_version_id),
  KEY production_orders_operator_user_id_idx (operator_user_id),
  CONSTRAINT production_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT production_orders_formulation_version_id_fkey FOREIGN KEY (formulation_version_id) REFERENCES formulation_versions(id),
  CONSTRAINT production_orders_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT production_orders_operator_user_id_fkey FOREIGN KEY (operator_user_id) REFERENCES users(id)
);

CREATE TABLE production_consumptions (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NOT NULL,
  raw_material_master_id VARCHAR(191) NOT NULL,
  raw_material_lot_id VARCHAR(191) NULL,
  formulation_ingredient_id VARCHAR(191) NULL,
  required_quantity DOUBLE NOT NULL,
  used_quantity DOUBLE NULL,
  waste_quantity DOUBLE NOT NULL DEFAULT 0,
  unit VARCHAR(191) NOT NULL DEFAULT 'g',
  substitution_authorized BOOLEAN NOT NULL DEFAULT false,
  observations TEXT NULL,
  confirmed_at DATETIME(3) NULL,
  confirmed_by_user_id VARCHAR(191) NULL,
  inventory_movement_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  KEY production_consumptions_organization_id_idx (organization_id),
  KEY production_consumptions_order_id_idx (production_order_id),
  KEY production_consumptions_raw_material_master_id_idx (raw_material_master_id),
  KEY production_consumptions_raw_material_lot_id_idx (raw_material_lot_id),
  CONSTRAINT production_consumptions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT production_consumptions_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id),
  CONSTRAINT production_consumptions_raw_material_master_id_fkey FOREIGN KEY (raw_material_master_id) REFERENCES raw_material_masters(id),
  CONSTRAINT production_consumptions_raw_material_lot_id_fkey FOREIGN KEY (raw_material_lot_id) REFERENCES raw_material_lots(id),
  CONSTRAINT production_consumptions_confirmed_by_user_id_fkey FOREIGN KEY (confirmed_by_user_id) REFERENCES users(id)
);

CREATE TABLE production_logs (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NOT NULL,
  type ENUM('inicio','fin','pausa','reanudacion','incidencia','observacion','parametro') NOT NULL,
  operator_user_id VARCHAR(191) NOT NULL,
  temperature DOUBLE NULL,
  time_minutes DOUBLE NULL,
  agitation_speed DOUBLE NULL,
  observations TEXT NULL,
  incidence TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY production_logs_organization_id_idx (organization_id),
  KEY production_logs_order_id_idx (production_order_id),
  KEY production_logs_operator_user_id_idx (operator_user_id),
  CONSTRAINT production_logs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT production_logs_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id),
  CONSTRAINT production_logs_operator_user_id_fkey FOREIGN KEY (operator_user_id) REFERENCES users(id)
);

CREATE TABLE production_checklist_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NOT NULL,
  label VARCHAR(191) NOT NULL,
  required BOOLEAN NOT NULL DEFAULT true,
  completed BOOLEAN NOT NULL DEFAULT false,
  completed_at DATETIME(3) NULL,
  completed_by_user_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  KEY production_checklist_items_organization_id_idx (organization_id),
  KEY production_checklist_items_order_id_idx (production_order_id),
  CONSTRAINT production_checklist_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT production_checklist_items_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id),
  CONSTRAINT production_checklist_items_completed_by_user_id_fkey FOREIGN KEY (completed_by_user_id) REFERENCES users(id)
);

CREATE TABLE production_process_parameters (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NOT NULL,
  temperature DOUBLE NULL,
  time_minutes DOUBLE NULL,
  speed DOUBLE NULL,
  ph DOUBLE NULL,
  viscosity VARCHAR(191) NULL,
  obtained_weight DOUBLE NULL,
  observations TEXT NULL,
  recorded_by_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY production_process_parameters_organization_id_idx (organization_id),
  KEY production_process_parameters_order_id_idx (production_order_id),
  CONSTRAINT production_process_parameters_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT production_process_parameters_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id)
);

CREATE TABLE finished_product_lots (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NOT NULL,
  lot_code VARCHAR(191) NOT NULL,
  produced_at DATETIME(3) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  quantity_obtained DOUBLE NOT NULL,
  unit VARCHAR(191) NOT NULL DEFAULT 'g',
  expected_yield DOUBLE NOT NULL,
  actual_yield DOUBLE NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY finished_product_lots_order_unique (production_order_id),
  KEY finished_product_lots_organization_id_idx (organization_id),
  CONSTRAINT finished_product_lots_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT finished_product_lots_order_id_fkey FOREIGN KEY (production_order_id) REFERENCES production_orders(id),
  CONSTRAINT finished_product_lots_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);
