ALTER TABLE raw_material_commercial_products
  ADD COLUMN permanent_code VARCHAR(191) NULL,
  ADD COLUMN presentation VARCHAR(191) NULL,
  ADD COLUMN presentation_quantity DOUBLE NULL,
  ADD COLUMN unit VARCHAR(191) NULL,
  ADD COLUMN price DOUBLE NULL,
  ADD COLUMN tax_rate DOUBLE NULL,
  ADD COLUMN shipping_cost DOUBLE NULL,
  ADD COLUMN minimum_purchase DOUBLE NULL,
  ADD COLUMN price_valid_until DATETIME(3) NULL,
  ADD COLUMN quoted_at DATETIME(3) NULL,
  ADD COLUMN observations TEXT NULL;

CREATE UNIQUE INDEX rmcp_org_perm_code_key ON raw_material_commercial_products(organization_id, permanent_code);

CREATE TABLE raw_material_price_history (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  commercial_product_id VARCHAR(191) NOT NULL,
  supplier_id VARCHAR(191) NULL,
  previous_price DOUBLE NULL,
  new_price DOUBLE NOT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  tax_rate DOUBLE NULL,
  shipping_cost DOUBLE NULL,
  valid_until DATETIME(3) NULL,
  quoted_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  reason VARCHAR(191) NULL,
  evidence_reference VARCHAR(191) NULL,
  created_by_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY raw_material_price_history_organization_id_idx (organization_id),
  KEY raw_material_price_history_commercial_product_id_idx (commercial_product_id),
  KEY raw_material_price_history_supplier_id_idx (supplier_id),
  CONSTRAINT raw_material_price_history_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT raw_material_price_history_commercial_product_id_fkey FOREIGN KEY (commercial_product_id) REFERENCES raw_material_commercial_products(id),
  CONSTRAINT raw_material_price_history_supplier_id_fkey FOREIGN KEY (supplier_id) REFERENCES raw_material_suppliers(id),
  CONSTRAINT raw_material_price_history_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE cost_scenarios (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  formulation_version_id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  batch_size DOUBLE NOT NULL,
  batch_unit VARCHAR(191) NOT NULL DEFAULT 'g',
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  exchange_rate DOUBLE NOT NULL DEFAULT 1,
  exchange_rate_date DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  provider_strategy VARCHAR(191) NOT NULL DEFAULT 'precio_reciente',
  additional_costs_json JSON NOT NULL,
  margin_percent DOUBLE NOT NULL DEFAULT 0,
  markup_percent DOUBLE NOT NULL DEFAULT 0,
  subtotal_ingredients DOUBLE NOT NULL DEFAULT 0,
  subtotal_additional DOUBLE NOT NULL DEFAULT 0,
  total_cost DOUBLE NOT NULL DEFAULT 0,
  cost_per_kg DOUBLE NULL,
  wholesale_price DOUBLE NULL,
  retail_price DOUBLE NULL,
  suggested_price DOUBLE NULL,
  alerts_json JSON NOT NULL,
  created_by_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY cost_scenarios_organization_id_idx (organization_id),
  KEY cost_scenarios_formulation_version_id_idx (formulation_version_id),
  CONSTRAINT cost_scenarios_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT cost_scenarios_formulation_version_id_fkey FOREIGN KEY (formulation_version_id) REFERENCES formulation_versions(id),
  CONSTRAINT cost_scenarios_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE cost_scenario_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  cost_scenario_id VARCHAR(191) NOT NULL,
  formulation_ingredient_id VARCHAR(191) NOT NULL,
  commercial_product_id VARCHAR(191) NULL,
  display_name VARCHAR(191) NOT NULL,
  phase VARCHAR(191) NOT NULL,
  percentage DOUBLE NOT NULL,
  grams DOUBLE NOT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  unit_cost DOUBLE NULL,
  line_cost DOUBLE NULL,
  cost_share_percent DOUBLE NULL,
  price_date DATETIME(3) NULL,
  trace_json JSON NOT NULL,
  KEY cost_scenario_items_organization_id_idx (organization_id),
  KEY cost_scenario_items_cost_scenario_id_idx (cost_scenario_id),
  KEY cost_scenario_items_formulation_ingredient_id_idx (formulation_ingredient_id),
  CONSTRAINT cost_scenario_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT cost_scenario_items_cost_scenario_id_fkey FOREIGN KEY (cost_scenario_id) REFERENCES cost_scenarios(id),
  CONSTRAINT cost_scenario_items_formulation_ingredient_id_fkey FOREIGN KEY (formulation_ingredient_id) REFERENCES formulation_ingredients(id),
  CONSTRAINT cost_scenario_items_commercial_product_id_fkey FOREIGN KEY (commercial_product_id) REFERENCES raw_material_commercial_products(id)
);
