CREATE TABLE quality_specifications (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NULL,
  version_number INT NOT NULL DEFAULT 1,
  status ENUM('borrador','en_revision','aprobada','obsoleta','archivada') NOT NULL DEFAULT 'borrador',
  effective_from DATETIME(3) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  document_id VARCHAR(191) NULL,
  locked BOOLEAN NOT NULL DEFAULT false,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_specifications_permanent_code_key (permanent_code),
  KEY quality_specifications_organization_id_idx (organization_id),
  KEY quality_specifications_entity_idx (entity_type, entity_id),
  KEY quality_specifications_status_idx (status),
  CONSTRAINT quality_specifications_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_specifications_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT quality_specifications_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE quality_specification_criteria (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  specification_id VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  min_limit DECIMAL(12,4) NULL,
  max_limit DECIMAL(12,4) NULL,
  unit VARCHAR(191) NULL,
  method_id VARCHAR(191) NULL,
  frequency VARCHAR(191) NULL,
  criticality VARCHAR(191) NOT NULL DEFAULT 'media',
  order_index INT NOT NULL DEFAULT 0,
  KEY quality_specification_criteria_organization_id_idx (organization_id),
  KEY quality_specification_criteria_specification_id_idx (specification_id),
  CONSTRAINT quality_specification_criteria_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_specification_criteria_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES quality_specifications(id)
);

CREATE TABLE quality_sampling_plans (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  material_type VARCHAR(191) NOT NULL,
  supplier_name VARCHAR(191) NULL,
  category VARCHAR(191) NULL,
  product_name VARCHAR(191) NULL,
  risk_level VARCHAR(191) NOT NULL DEFAULT 'medio',
  lot_size_range VARCHAR(191) NULL,
  inspection_level VARCHAR(191) NOT NULL DEFAULT 'normal',
  method VARCHAR(191) NOT NULL,
  sample_quantity INT NOT NULL,
  sampling_points_json JSON NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  instructions TEXT NOT NULL,
  acceptance_criteria TEXT NOT NULL,
  document_id VARCHAR(191) NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_sampling_plans_permanent_code_key (permanent_code),
  KEY quality_sampling_plans_organization_id_idx (organization_id),
  KEY quality_sampling_plans_material_type_idx (material_type),
  CONSTRAINT quality_sampling_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_sampling_plans_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE quality_inspections (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  inspection_type VARCHAR(191) NOT NULL DEFAULT 'recepcion',
  lot_id VARCHAR(191) NULL,
  supplier_name VARCHAR(191) NULL,
  commercial_product_id VARCHAR(191) NULL,
  received_quantity DECIMAL(12,3) NULL,
  unit VARCHAR(191) NULL,
  package_integrity VARCHAR(191) NULL,
  identification VARCHAR(191) NULL,
  color VARCHAR(191) NULL,
  odor VARCHAR(191) NULL,
  appearance VARCHAR(191) NULL,
  initial_result VARCHAR(191) NULL,
  observations TEXT NULL,
  status ENUM('pendiente','en_inspeccion','en_cuarentena','aprobado','aprobado_con_observaciones','rechazado','bloqueado') NOT NULL DEFAULT 'pendiente',
  specification_id VARCHAR(191) NULL,
  evidence_document_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  inspected_at DATETIME(3) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_inspections_permanent_code_key (permanent_code),
  KEY quality_inspections_organization_id_idx (organization_id),
  KEY quality_inspections_lot_id_idx (lot_id),
  KEY quality_inspections_status_idx (status),
  CONSTRAINT quality_inspections_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_inspections_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES quality_specifications(id),
  CONSTRAINT quality_inspections_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id),
  CONSTRAINT quality_inspections_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE quality_process_controls (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NULL,
  stage VARCHAR(191) NOT NULL,
  lot_code VARCHAR(191) NULL,
  operator_user_id VARCHAR(191) NULL,
  analyst_user_id VARCHAR(191) NULL,
  specification_id VARCHAR(191) NULL,
  method_id VARCHAR(191) NULL,
  measured_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  results_json JSON NOT NULL,
  conformity_status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  evidence_document_id VARCHAR(191) NULL,
  observations TEXT NULL,
  KEY quality_process_controls_organization_id_idx (organization_id),
  KEY quality_process_controls_production_order_id_idx (production_order_id),
  CONSTRAINT quality_process_controls_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE quality_finished_controls (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  production_order_id VARCHAR(191) NULL,
  finished_lot_code VARCHAR(191) NULL,
  specification_id VARCHAR(191) NULL,
  results_json JSON NOT NULL,
  conformity_status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  evidence_document_id VARCHAR(191) NULL,
  observations TEXT NULL,
  controlled_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY quality_finished_controls_organization_id_idx (organization_id),
  KEY quality_finished_controls_production_order_id_idx (production_order_id),
  CONSTRAINT quality_finished_controls_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE quality_releases (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  release_type VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NOT NULL,
  inspection_id VARCHAR(191) NULL,
  specification_id VARCHAR(191) NOT NULL,
  decision ENUM('liberar','reprocesar','reclasificar','devolver','destruir','usar_bajo_desviacion','mantener_en_cuarentena','rechazar') NOT NULL,
  conclusion TEXT NOT NULL,
  reason TEXT NOT NULL,
  digital_confirmation VARCHAR(191) NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  closed BOOLEAN NOT NULL DEFAULT true,
  decided_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY quality_releases_permanent_code_key (permanent_code),
  KEY quality_releases_organization_id_idx (organization_id),
  KEY quality_releases_entity_idx (entity_type, entity_id),
  KEY quality_releases_decision_idx (decision),
  CONSTRAINT quality_releases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_releases_inspection_id_fkey FOREIGN KEY (inspection_id) REFERENCES quality_inspections(id),
  CONSTRAINT quality_releases_specification_id_fkey FOREIGN KEY (specification_id) REFERENCES quality_specifications(id),
  CONSTRAINT quality_releases_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id),
  CONSTRAINT quality_releases_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE quality_deviations (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  deviation_type VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  severity VARCHAR(191) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  affected_entity_type VARCHAR(191) NOT NULL,
  affected_entity_id VARCHAR(191) NULL,
  preliminary_cause TEXT NULL,
  containment TEXT NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'abierta',
  occurred_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_deviations_permanent_code_key (permanent_code),
  KEY quality_deviations_organization_id_idx (organization_id),
  KEY quality_deviations_status_idx (status),
  CONSTRAINT quality_deviations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_deviations_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT quality_deviations_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE quality_non_conformities (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  origin VARCHAR(191) NOT NULL,
  ncf_type VARCHAR(191) NOT NULL,
  severity VARCHAR(191) NOT NULL,
  lot_id VARCHAR(191) NULL,
  product_name VARCHAR(191) NULL,
  supplier_name VARCHAR(191) NULL,
  production_order_id VARCHAR(191) NULL,
  lab_reference_id VARCHAR(191) NULL,
  description TEXT NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'abierta',
  disposition_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_non_conformities_permanent_code_key (permanent_code),
  KEY quality_non_conformities_organization_id_idx (organization_id),
  KEY quality_non_conformities_status_idx (status),
  CONSTRAINT quality_non_conformities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_non_conformities_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id),
  CONSTRAINT quality_non_conformities_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE quality_capa_actions (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  action_text TEXT NOT NULL,
  action_type VARCHAR(191) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  target_date DATETIME(3) NOT NULL,
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  root_cause TEXT NULL,
  evidence_document_id VARCHAR(191) NULL,
  effectiveness_check TEXT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'abierta',
  deviation_id VARCHAR(191) NULL,
  non_conformity_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY quality_capa_actions_permanent_code_key (permanent_code),
  KEY quality_capa_actions_organization_id_idx (organization_id),
  KEY quality_capa_actions_status_idx (status),
  KEY quality_capa_actions_target_date_idx (target_date),
  CONSTRAINT quality_capa_actions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_capa_actions_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT quality_capa_actions_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id),
  CONSTRAINT quality_capa_actions_deviation_id_fkey FOREIGN KEY (deviation_id) REFERENCES quality_deviations(id),
  CONSTRAINT quality_capa_actions_non_conformity_id_fkey FOREIGN KEY (non_conformity_id) REFERENCES quality_non_conformities(id)
);

CREATE TABLE quality_dispositions (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NOT NULL,
  decision ENUM('liberar','reprocesar','reclasificar','devolver','destruir','usar_bajo_desviacion','mantener_en_cuarentena','rechazar') NOT NULL,
  reason TEXT NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  non_conformity_id VARCHAR(191) NULL,
  decided_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY quality_dispositions_permanent_code_key (permanent_code),
  KEY quality_dispositions_organization_id_idx (organization_id),
  KEY quality_dispositions_entity_idx (entity_type, entity_id),
  CONSTRAINT quality_dispositions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_dispositions_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT quality_dispositions_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id),
  CONSTRAINT quality_dispositions_non_conformity_id_fkey FOREIGN KEY (non_conformity_id) REFERENCES quality_non_conformities(id)
);

CREATE TABLE quality_reports (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  report_type VARCHAR(191) NOT NULL,
  title VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NOT NULL,
  summary TEXT NOT NULL,
  document_id VARCHAR(191) NULL,
  created_by_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY quality_reports_organization_id_idx (organization_id),
  KEY quality_reports_entity_idx (entity_type, entity_id),
  CONSTRAINT quality_reports_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT quality_reports_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id),
  CONSTRAINT quality_reports_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);
