CREATE TABLE crm_leads (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  commercial_name VARCHAR(191) NOT NULL,
  legal_name VARCHAR(191) NULL,
  person_type VARCHAR(191) NOT NULL,
  industry VARCHAR(191) NULL,
  segment VARCHAR(191) NULL,
  channel VARCHAR(191) NULL,
  origin VARCHAR(191) NULL,
  status ENUM('nuevo','contactado','calificado','en_seguimiento','convertido','descartado','inactivo') NOT NULL DEFAULT 'nuevo',
  responsible_user_id VARCHAR(191) NOT NULL,
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  city VARCHAR(191) NULL,
  state VARCHAR(191) NULL,
  country VARCHAR(191) NULL DEFAULT 'Mexico',
  website VARCHAR(191) NULL,
  observations TEXT NULL,
  tags_json JSON NULL,
  document_id VARCHAR(191) NULL,
  converted_customer_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY crm_leads_permanent_code_key (permanent_code),
  KEY crm_leads_organization_id_idx (organization_id),
  KEY crm_leads_status_idx (status),
  CONSTRAINT crm_leads_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT crm_leads_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT crm_leads_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE crm_customers (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  lead_id VARCHAR(191) NULL,
  legal_name VARCHAR(191) NOT NULL,
  commercial_name VARCHAR(191) NOT NULL,
  rfc_prepared VARCHAR(191) NULL,
  customer_type VARCHAR(191) NOT NULL,
  segment VARCHAR(191) NULL,
  commercial_terms TEXT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  price_list_id VARCHAR(191) NULL,
  credit_prepared BOOLEAN NOT NULL DEFAULT false,
  addresses_json JSON NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY crm_customers_permanent_code_key (permanent_code),
  UNIQUE KEY crm_customers_lead_id_key (lead_id),
  KEY crm_customers_organization_id_idx (organization_id),
  KEY crm_customers_status_idx (status),
  CONSTRAINT crm_customers_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT crm_customers_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
  CONSTRAINT crm_customers_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE crm_contacts (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  lead_id VARCHAR(191) NULL,
  customer_id VARCHAR(191) NULL,
  full_name VARCHAR(191) NOT NULL,
  position VARCHAR(191) NULL,
  area VARCHAR(191) NULL,
  email VARCHAR(191) NULL,
  phone VARCHAR(191) NULL,
  whatsapp VARCHAR(191) NULL,
  preferred_channel VARCHAR(191) NULL,
  purchasing_responsible BOOLEAN NOT NULL DEFAULT false,
  technical_responsible BOOLEAN NOT NULL DEFAULT false,
  observations TEXT NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY crm_contacts_permanent_code_key (permanent_code),
  KEY crm_contacts_organization_id_idx (organization_id),
  KEY crm_contacts_lead_id_idx (lead_id),
  KEY crm_contacts_customer_id_idx (customer_id),
  CONSTRAINT crm_contacts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT crm_contacts_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
  CONSTRAINT crm_contacts_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id)
);

CREATE TABLE crm_activities (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  activity_type VARCHAR(191) NOT NULL,
  related_entity_type VARCHAR(191) NOT NULL,
  related_entity_id VARCHAR(191) NOT NULL,
  lead_id VARCHAR(191) NULL,
  customer_id VARCHAR(191) NULL,
  created_by_user_id VARCHAR(191) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  scheduled_at DATETIME(3) NOT NULL,
  result TEXT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  reminder_prepared BOOLEAN NOT NULL DEFAULT false,
  evidence_document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY crm_activities_permanent_code_key (permanent_code),
  KEY crm_activities_organization_id_idx (organization_id),
  KEY crm_activities_related_idx (related_entity_type, related_entity_id),
  CONSTRAINT crm_activities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT crm_activities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
  CONSTRAINT crm_activities_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id),
  CONSTRAINT crm_activities_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id),
  CONSTRAINT crm_activities_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT crm_activities_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE crm_opportunities (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  lead_id VARCHAR(191) NULL,
  customer_id VARCHAR(191) NULL,
  name VARCHAR(191) NOT NULL,
  products_interest_json JSON NULL,
  estimated_quantity DECIMAL(12,3) NULL,
  estimated_value DECIMAL(14,2) NOT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  probability INT NOT NULL DEFAULT 25,
  estimated_close_date DATETIME(3) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  competition VARCHAR(191) NULL,
  need TEXT NULL,
  observations TEXT NULL,
  stage ENUM('deteccion','calificacion','diagnostico','propuesta','negociacion','ganada','perdida','pausada') NOT NULL DEFAULT 'deteccion',
  status VARCHAR(191) NOT NULL DEFAULT 'activa',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY crm_opportunities_permanent_code_key (permanent_code),
  KEY crm_opportunities_organization_id_idx (organization_id),
  KEY crm_opportunities_stage_idx (stage),
  CONSTRAINT crm_opportunities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT crm_opportunities_lead_id_fkey FOREIGN KEY (lead_id) REFERENCES crm_leads(id),
  CONSTRAINT crm_opportunities_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id),
  CONSTRAINT crm_opportunities_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE sales_products (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  finished_product_lot_id VARCHAR(191) NULL,
  presentation VARCHAR(191) NOT NULL,
  sales_unit VARCHAR(191) NOT NULL,
  formulation_family_id VARCHAR(191) NULL,
  formulation_version_id VARCHAR(191) NULL,
  packaging VARCHAR(191) NULL,
  label_info VARCHAR(191) NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  price DECIMAL(14,2) NOT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  tax_prepared BOOLEAN NOT NULL DEFAULT true,
  availability VARCHAR(191) NOT NULL DEFAULT 'consultar',
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY sales_products_permanent_code_key (permanent_code),
  KEY sales_products_organization_id_idx (organization_id),
  KEY sales_products_status_idx (status),
  CONSTRAINT sales_products_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_products_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE sales_price_lists (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  version_number INT NOT NULL DEFAULT 1,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  channel VARCHAR(191) NULL,
  segment VARCHAR(191) NULL,
  customer_id VARCHAR(191) NULL,
  volume_min DECIMAL(12,3) NULL,
  valid_from DATETIME(3) NOT NULL,
  valid_until DATETIME(3) NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'vigente',
  items_json JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY sales_price_lists_permanent_code_key (permanent_code),
  KEY sales_price_lists_organization_id_idx (organization_id),
  KEY sales_price_lists_status_idx (status),
  CONSTRAINT sales_price_lists_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE sales_quotes (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  customer_id VARCHAR(191) NOT NULL,
  opportunity_id VARCHAR(191) NULL,
  contact_id VARCHAR(191) NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  exchange_rate DECIMAL(12,4) NULL,
  subtotal DECIMAL(14,2) NOT NULL,
  discount_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  total DECIMAL(14,2) NOT NULL,
  valid_until DATETIME(3) NULL,
  conditions TEXT NULL,
  estimated_date DATETIME(3) NULL,
  notes TEXT NULL,
  document_id VARCHAR(191) NULL,
  status ENUM('borrador','enviada','vista','en_negociacion','aceptada','rechazada','vencida','cancelada','convertida') NOT NULL DEFAULT 'borrador',
  converted_order_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY sales_quotes_permanent_code_key (permanent_code),
  KEY sales_quotes_organization_id_idx (organization_id),
  KEY sales_quotes_status_idx (status),
  CONSTRAINT sales_quotes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_quotes_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id),
  CONSTRAINT sales_quotes_opportunity_id_fkey FOREIGN KEY (opportunity_id) REFERENCES crm_opportunities(id),
  CONSTRAINT sales_quotes_contact_id_fkey FOREIGN KEY (contact_id) REFERENCES crm_contacts(id),
  CONSTRAINT sales_quotes_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE sales_quote_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  quote_id VARCHAR(191) NOT NULL,
  product_id VARCHAR(191) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL,
  unit_price DECIMAL(14,4) NOT NULL,
  discount_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
  tax_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
  cost_reference DECIMAL(14,4) NULL,
  margin DECIMAL(8,4) NULL,
  line_total DECIMAL(14,2) NOT NULL,
  KEY sales_quote_items_organization_id_idx (organization_id),
  KEY sales_quote_items_quote_id_idx (quote_id),
  CONSTRAINT sales_quote_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_quote_items_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES sales_quotes(id),
  CONSTRAINT sales_quote_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES sales_products(id)
);

CREATE TABLE sales_approvals (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  quote_id VARCHAR(191) NOT NULL,
  approval_type VARCHAR(191) NOT NULL,
  approver_user_id VARCHAR(191) NOT NULL,
  decision VARCHAR(191) NOT NULL,
  comment TEXT NULL,
  reason TEXT NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  decided_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY sales_approvals_organization_id_idx (organization_id),
  KEY sales_approvals_quote_id_idx (quote_id),
  CONSTRAINT sales_approvals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_approvals_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES sales_quotes(id),
  CONSTRAINT sales_approvals_approver_user_id_fkey FOREIGN KEY (approver_user_id) REFERENCES users(id)
);

CREATE TABLE sales_orders (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  customer_id VARCHAR(191) NOT NULL,
  quote_id VARCHAR(191) NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  subtotal DECIMAL(14,2) NOT NULL,
  discount_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  tax_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  shipping_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  total DECIMAL(14,2) NOT NULL,
  requested_date DATETIME(3) NULL,
  promised_date DATETIME(3) NULL,
  delivery_address_json JSON NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  status ENUM('borrador','confirmado','en_validacion','en_preparacion','en_produccion','listo','parcialmente_entregado','entregado','cancelado','cerrado') NOT NULL DEFAULT 'borrador',
  availability_snapshot_json JSON NULL,
  production_suggestion_json JSON NULL,
  observations TEXT NULL,
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY sales_orders_permanent_code_key (permanent_code),
  UNIQUE KEY sales_orders_quote_id_key (quote_id),
  KEY sales_orders_organization_id_idx (organization_id),
  KEY sales_orders_status_idx (status),
  CONSTRAINT sales_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_orders_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id),
  CONSTRAINT sales_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES sales_quotes(id),
  CONSTRAINT sales_orders_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT sales_orders_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE sales_order_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NOT NULL,
  product_id VARCHAR(191) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  quantity_delivered DECIMAL(12,3) NOT NULL DEFAULT 0,
  unit VARCHAR(191) NOT NULL,
  unit_price DECIMAL(14,4) NOT NULL,
  discount_rate DECIMAL(8,4) NOT NULL DEFAULT 0,
  line_total DECIMAL(14,2) NOT NULL,
  KEY sales_order_items_organization_id_idx (organization_id),
  KEY sales_order_items_order_id_idx (order_id),
  CONSTRAINT sales_order_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES sales_orders(id),
  CONSTRAINT sales_order_items_product_id_fkey FOREIGN KEY (product_id) REFERENCES sales_products(id)
);

CREATE TABLE sales_deliveries (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NOT NULL,
  items_json JSON NOT NULL,
  lot_ids_json JSON NULL,
  delivered_at DATETIME(3) NULL,
  address_json JSON NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  carrier_prepared VARCHAR(191) NULL,
  evidence_document_id VARCHAR(191) NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'preparada',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY sales_deliveries_permanent_code_key (permanent_code),
  KEY sales_deliveries_organization_id_idx (organization_id),
  KEY sales_deliveries_order_id_idx (order_id),
  CONSTRAINT sales_deliveries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_deliveries_order_id_fkey FOREIGN KEY (order_id) REFERENCES sales_orders(id),
  CONSTRAINT sales_deliveries_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT sales_deliveries_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE sales_samples (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  product_id VARCHAR(191) NOT NULL,
  finished_lot_id VARCHAR(191) NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL,
  customer_id VARCHAR(191) NOT NULL,
  contact_id VARCHAR(191) NULL,
  sent_at DATETIME(3) NOT NULL,
  objective TEXT NOT NULL,
  cost DECIMAL(14,2) NULL,
  follow_up TEXT NULL,
  result TEXT NULL,
  evidence_document_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY sales_samples_permanent_code_key (permanent_code),
  KEY sales_samples_organization_id_idx (organization_id),
  KEY sales_samples_customer_id_idx (customer_id),
  CONSTRAINT sales_samples_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT sales_samples_product_id_fkey FOREIGN KEY (product_id) REFERENCES sales_products(id),
  CONSTRAINT sales_samples_customer_id_fkey FOREIGN KEY (customer_id) REFERENCES crm_customers(id),
  CONSTRAINT sales_samples_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT sales_samples_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);
