CREATE TABLE ai_rules (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  rule_type VARCHAR(191) NOT NULL,
  condition_json JSON NOT NULL,
  severity ENUM('informativa','baja','media','alta','critica') NOT NULL DEFAULT 'media',
  result_message TEXT NOT NULL,
  source TEXT NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  version_number INT NOT NULL DEFAULT 1,
  status ENUM('borrador','en_revision','validada','rechazada','obsoleta','archivada') NOT NULL DEFAULT 'borrador',
  responsible_user_id VARCHAR(191) NOT NULL,
  validated_at DATETIME(3) NULL,
  valid_from DATETIME(3) NULL,
  valid_until DATETIME(3) NULL,
  confidence DECIMAL(8,4) NOT NULL DEFAULT 0.8,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY ai_rules_permanent_code_key (permanent_code),
  KEY ai_rules_organization_id_idx (organization_id),
  KEY ai_rules_rule_type_idx (rule_type),
  KEY ai_rules_status_idx (status),
  CONSTRAINT ai_rules_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_rules_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT ai_rules_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE ai_rule_evaluations (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  rule_id VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NOT NULL,
  result VARCHAR(191) NOT NULL,
  severity ENUM('informativa','baja','media','alta','critica') NOT NULL,
  evidence_json JSON NULL,
  evaluated_by_user_id VARCHAR(191) NULL,
  rule_version_number INT NOT NULL,
  evaluated_data_json JSON NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ai_rule_evaluations_permanent_code_key (permanent_code),
  KEY ai_rule_evaluations_organization_id_idx (organization_id),
  KEY ai_rule_evaluations_entity_idx (entity_type, entity_id),
  CONSTRAINT ai_rule_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_rule_evaluations_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES ai_rules(id),
  CONSTRAINT ai_rule_evaluations_evaluated_by_user_id_fkey FOREIGN KEY (evaluated_by_user_id) REFERENCES users(id)
);

CREATE TABLE ai_alerts (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  rule_id VARCHAR(191) NULL,
  evaluation_id VARCHAR(191) NULL,
  entity_type VARCHAR(191) NOT NULL,
  entity_id VARCHAR(191) NOT NULL,
  detected TEXT NOT NULL,
  explanation TEXT NOT NULL,
  source TEXT NOT NULL,
  confidence DECIMAL(8,4) NOT NULL,
  severity ENUM('informativa','baja','media','alta','critica') NOT NULL,
  suggested_action TEXT NULL,
  validation_responsible VARCHAR(191) NULL,
  output_type ENUM('dato_documental','calculo','inferencia','sugerencia','alerta','informacion_insuficiente') NOT NULL DEFAULT 'alerta',
  status VARCHAR(191) NOT NULL DEFAULT 'abierta',
  evidence_document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ai_alerts_permanent_code_key (permanent_code),
  KEY ai_alerts_organization_id_idx (organization_id),
  KEY ai_alerts_status_idx (status),
  KEY ai_alerts_entity_idx (entity_type, entity_id),
  CONSTRAINT ai_alerts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_alerts_rule_id_fkey FOREIGN KEY (rule_id) REFERENCES ai_rules(id),
  CONSTRAINT ai_alerts_evaluation_id_fkey FOREIGN KEY (evaluation_id) REFERENCES ai_rule_evaluations(id),
  CONSTRAINT ai_alerts_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE ai_queries (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  query_text TEXT NOT NULL,
  module_scope VARCHAR(191) NULL,
  entity_type VARCHAR(191) NULL,
  entity_id VARCHAR(191) NULL,
  user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ai_queries_permanent_code_key (permanent_code),
  KEY ai_queries_organization_id_idx (organization_id),
  KEY ai_queries_user_id_idx (user_id),
  CONSTRAINT ai_queries_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_queries_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ai_responses (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  query_id VARCHAR(191) NOT NULL,
  answer TEXT NOT NULL,
  sources_json JSON NOT NULL,
  documents_json JSON NULL,
  fragments_json JSON NULL,
  confidence DECIMAL(8,4) NOT NULL,
  information_date DATETIME(3) NULL,
  warnings_json JSON NULL,
  validation_status VARCHAR(191) NOT NULL DEFAULT 'no_validada',
  output_type ENUM('dato_documental','calculo','inferencia','sugerencia','alerta','informacion_insuficiente') NOT NULL DEFAULT 'dato_documental',
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ai_responses_permanent_code_key (permanent_code),
  UNIQUE KEY ai_responses_query_id_key (query_id),
  KEY ai_responses_organization_id_idx (organization_id),
  CONSTRAINT ai_responses_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_responses_query_id_fkey FOREIGN KEY (query_id) REFERENCES ai_queries(id),
  CONSTRAINT ai_responses_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE learning_events (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  context VARCHAR(191) NOT NULL,
  input_json JSON NOT NULL,
  proposed_output_json JSON NULL,
  correction_json JSON NULL,
  user_id VARCHAR(191) NOT NULL,
  entity_type VARCHAR(191) NULL,
  entity_id VARCHAR(191) NULL,
  model_or_rule VARCHAR(191) NULL,
  review_status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY learning_events_permanent_code_key (permanent_code),
  KEY learning_events_organization_id_idx (organization_id),
  KEY learning_events_entity_idx (entity_type, entity_id),
  CONSTRAINT learning_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT learning_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE ai_source_configs (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NULL,
  permanent_code VARCHAR(191) NOT NULL,
  source_type VARCHAR(191) NOT NULL,
  author VARCHAR(191) NULL,
  source_organization VARCHAR(191) NULL,
  source_date DATETIME(3) NULL,
  valid_until DATETIME(3) NULL,
  confidence DECIMAL(8,4) NOT NULL,
  priority INT NOT NULL DEFAULT 5,
  status VARCHAR(191) NOT NULL DEFAULT 'activo',
  responsible_user_id VARCHAR(191) NOT NULL,
  last_reviewed_at DATETIME(3) NULL,
  provider VARCHAR(191) NULL,
  model VARCHAR(191) NULL,
  endpoint VARCHAR(191) NULL,
  limits_json JSON NULL,
  cost_policy_json JSON NULL,
  usage_policy TEXT NULL,
  environment VARCHAR(191) NOT NULL DEFAULT 'demo',
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY ai_source_configs_permanent_code_key (permanent_code),
  KEY ai_source_configs_organization_id_idx (organization_id),
  KEY ai_source_configs_source_type_idx (source_type),
  KEY ai_source_configs_status_idx (status),
  CONSTRAINT ai_source_configs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT ai_source_configs_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT ai_source_configs_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);
