CREATE TABLE lab_projects (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  project_type VARCHAR(191) NOT NULL,
  objective TEXT NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  status ENUM('borrador','planeado','activo','pausado','completado','cancelado','archivado') NOT NULL DEFAULT 'borrador',
  start_date DATETIME(3) NULL,
  target_date DATETIME(3) NULL,
  completed_at DATETIME(3) NULL,
  formulation_family_id VARCHAR(191) NULL,
  formulation_version_id VARCHAR(191) NULL,
  observations TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_projects_permanent_code_key (permanent_code),
  KEY lab_projects_organization_id_idx (organization_id),
  KEY lab_projects_responsible_user_id_idx (responsible_user_id),
  KEY lab_projects_formulation_version_id_idx (formulation_version_id),
  KEY lab_projects_status_idx (status),
  CONSTRAINT lab_projects_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_projects_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT lab_projects_formulation_family_id_fkey FOREIGN KEY (formulation_family_id) REFERENCES formulation_families(id),
  CONSTRAINT lab_projects_formulation_version_id_fkey FOREIGN KEY (formulation_version_id) REFERENCES formulation_versions(id)
);

CREATE TABLE lab_samples (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  project_id VARCHAR(191) NOT NULL,
  formulation_family_id VARCHAR(191) NULL,
  formulation_version_id VARCHAR(191) NULL,
  pilot_lot_code VARCHAR(191) NULL,
  prepared_at DATETIME(3) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL DEFAULT 'g',
  location VARCHAR(191) NULL,
  storage_conditions TEXT NULL,
  status ENUM('preparada','en_evaluacion','aprobada','rechazada','agotada','retenida','archivada') NOT NULL DEFAULT 'preparada',
  observations TEXT NULL,
  released BOOLEAN NOT NULL DEFAULT false,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_samples_permanent_code_key (permanent_code),
  KEY lab_samples_organization_id_idx (organization_id),
  KEY lab_samples_project_id_idx (project_id),
  KEY lab_samples_formulation_version_id_idx (formulation_version_id),
  KEY lab_samples_status_idx (status),
  CONSTRAINT lab_samples_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_samples_project_id_fkey FOREIGN KEY (project_id) REFERENCES lab_projects(id),
  CONSTRAINT lab_samples_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT lab_samples_formulation_family_id_fkey FOREIGN KEY (formulation_family_id) REFERENCES formulation_families(id),
  CONSTRAINT lab_samples_formulation_version_id_fkey FOREIGN KEY (formulation_version_id) REFERENCES formulation_versions(id)
);

CREATE TABLE lab_test_methods (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  description TEXT NOT NULL,
  preparation TEXT NULL,
  equipment TEXT NULL,
  conditions TEXT NULL,
  procedure_text TEXT NOT NULL,
  unit VARCHAR(191) NULL,
  acceptance_criteria TEXT NULL,
  references_text TEXT NULL,
  version_number INT NOT NULL DEFAULT 1,
  validation_status VARCHAR(191) NOT NULL DEFAULT 'borrador',
  locked BOOLEAN NOT NULL DEFAULT false,
  created_by_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_test_methods_permanent_code_key (permanent_code),
  KEY lab_test_methods_organization_id_idx (organization_id),
  KEY lab_test_methods_validation_status_idx (validation_status),
  CONSTRAINT lab_test_methods_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_test_methods_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE lab_test_plans (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  code VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  formulation_family_id VARCHAR(191) NULL,
  product_type_id VARCHAR(191) NULL,
  need_id VARCHAR(191) NULL,
  development_stage VARCHAR(191) NULL,
  sample_type VARCHAR(191) NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_test_plans_org_code_unique (organization_id, code),
  KEY lab_test_plans_organization_id_idx (organization_id),
  CONSTRAINT lab_test_plans_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);

CREATE TABLE lab_test_plan_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  plan_id VARCHAR(191) NOT NULL,
  method_id VARCHAR(191) NOT NULL,
  test_type VARCHAR(191) NOT NULL,
  required BOOLEAN NOT NULL DEFAULT true,
  order_index INT NOT NULL DEFAULT 0,
  KEY lab_test_plan_items_organization_id_idx (organization_id),
  KEY lab_test_plan_items_plan_id_idx (plan_id),
  KEY lab_test_plan_items_method_id_idx (method_id),
  CONSTRAINT lab_test_plan_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_test_plan_items_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES lab_test_plans(id),
  CONSTRAINT lab_test_plan_items_method_id_fkey FOREIGN KEY (method_id) REFERENCES lab_test_methods(id)
);

CREATE TABLE lab_instruments (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  instrument_type VARCHAR(191) NOT NULL,
  name VARCHAR(191) NOT NULL,
  manufacturer VARCHAR(191) NULL,
  model VARCHAR(191) NULL,
  serial_number VARCHAR(191) NULL,
  location VARCHAR(191) NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  last_calibration_at DATETIME(3) NULL,
  next_calibration_at DATETIME(3) NULL,
  responsible_user_id VARCHAR(191) NULL,
  observations TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_instruments_permanent_code_key (permanent_code),
  KEY lab_instruments_organization_id_idx (organization_id),
  KEY lab_instruments_instrument_type_idx (instrument_type),
  KEY lab_instruments_next_calibration_at_idx (next_calibration_at),
  CONSTRAINT lab_instruments_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_instruments_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE lab_tests (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  sample_id VARCHAR(191) NOT NULL,
  method_id VARCHAR(191) NOT NULL,
  test_type VARCHAR(191) NOT NULL,
  unit VARCHAR(191) NULL,
  specification TEXT NULL,
  numeric_result DECIMAL(12,4) NULL,
  qualitative_result TEXT NULL,
  instrument_id VARCHAR(191) NULL,
  analyst_user_id VARCHAR(191) NOT NULL,
  tested_at DATETIME(3) NOT NULL,
  status ENUM('pendiente','en_proceso','completado','repetido','invalidado','aprobado_tecnicamente') NOT NULL DEFAULT 'pendiente',
  conformity_status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  observations TEXT NULL,
  evidence_document_id VARCHAR(191) NULL,
  invalidated_reason TEXT NULL,
  repeated_from_test_id VARCHAR(191) NULL,
  released_locked BOOLEAN NOT NULL DEFAULT false,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_tests_permanent_code_key (permanent_code),
  KEY lab_tests_organization_id_idx (organization_id),
  KEY lab_tests_sample_id_idx (sample_id),
  KEY lab_tests_method_id_idx (method_id),
  KEY lab_tests_status_idx (status),
  KEY lab_tests_conformity_status_idx (conformity_status),
  CONSTRAINT lab_tests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_tests_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES lab_samples(id),
  CONSTRAINT lab_tests_method_id_fkey FOREIGN KEY (method_id) REFERENCES lab_test_methods(id),
  CONSTRAINT lab_tests_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES lab_instruments(id),
  CONSTRAINT lab_tests_analyst_user_id_fkey FOREIGN KEY (analyst_user_id) REFERENCES users(id),
  CONSTRAINT lab_tests_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE lab_stability_studies (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  sample_id VARCHAR(191) NOT NULL,
  condition_name VARCHAR(191) NOT NULL,
  temperature DECIMAL(8,2) NULL,
  humidity DECIMAL(8,2) NULL,
  light VARCHAR(191) NULL,
  packaging VARCHAR(191) NULL,
  duration_days INT NOT NULL,
  conclusion TEXT NULL,
  status ENUM('activo','inactivo','archivado') NOT NULL DEFAULT 'activo',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_stability_studies_permanent_code_key (permanent_code),
  KEY lab_stability_studies_organization_id_idx (organization_id),
  KEY lab_stability_studies_sample_id_idx (sample_id),
  CONSTRAINT lab_stability_studies_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_stability_studies_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES lab_samples(id)
);

CREATE TABLE lab_stability_points (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  study_id VARCHAR(191) NOT NULL,
  day_number INT NOT NULL,
  scheduled_at DATETIME(3) NOT NULL,
  evaluated_at DATETIME(3) NULL,
  test_id VARCHAR(191) NULL,
  result_summary TEXT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'pendiente',
  KEY lab_stability_points_organization_id_idx (organization_id),
  KEY lab_stability_points_study_id_idx (study_id),
  KEY lab_stability_points_scheduled_at_idx (scheduled_at),
  CONSTRAINT lab_stability_points_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_stability_points_study_id_fkey FOREIGN KEY (study_id) REFERENCES lab_stability_studies(id),
  CONSTRAINT lab_stability_points_test_id_fkey FOREIGN KEY (test_id) REFERENCES lab_tests(id)
);

CREATE TABLE lab_timeline_events (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  project_id VARCHAR(191) NULL,
  sample_id VARCHAR(191) NULL,
  event_type VARCHAR(191) NOT NULL,
  title VARCHAR(191) NOT NULL,
  description TEXT NULL,
  event_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  created_by_user_id VARCHAR(191) NOT NULL,
  KEY lab_timeline_events_organization_id_idx (organization_id),
  KEY lab_timeline_events_project_id_idx (project_id),
  KEY lab_timeline_events_sample_id_idx (sample_id),
  KEY lab_timeline_events_event_at_idx (event_at),
  CONSTRAINT lab_timeline_events_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_timeline_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES lab_projects(id),
  CONSTRAINT lab_timeline_events_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES lab_samples(id),
  CONSTRAINT lab_timeline_events_created_by_user_id_fkey FOREIGN KEY (created_by_user_id) REFERENCES users(id)
);

CREATE TABLE lab_non_conformities (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  project_id VARCHAR(191) NULL,
  sample_id VARCHAR(191) NULL,
  test_id VARCHAR(191) NULL,
  instrument_id VARCHAR(191) NULL,
  method_id VARCHAR(191) NULL,
  deviation TEXT NOT NULL,
  preliminary_cause TEXT NULL,
  action_plan TEXT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'abierta',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY lab_non_conformities_permanent_code_key (permanent_code),
  KEY lab_non_conformities_organization_id_idx (organization_id),
  KEY lab_non_conformities_sample_id_idx (sample_id),
  KEY lab_non_conformities_test_id_idx (test_id),
  KEY lab_non_conformities_status_idx (status),
  CONSTRAINT lab_non_conformities_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_non_conformities_project_id_fkey FOREIGN KEY (project_id) REFERENCES lab_projects(id),
  CONSTRAINT lab_non_conformities_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES lab_samples(id),
  CONSTRAINT lab_non_conformities_test_id_fkey FOREIGN KEY (test_id) REFERENCES lab_tests(id),
  CONSTRAINT lab_non_conformities_instrument_id_fkey FOREIGN KEY (instrument_id) REFERENCES lab_instruments(id),
  CONSTRAINT lab_non_conformities_method_id_fkey FOREIGN KEY (method_id) REFERENCES lab_test_methods(id),
  CONSTRAINT lab_non_conformities_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT lab_non_conformities_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE lab_technical_releases (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  sample_id VARCHAR(191) NOT NULL,
  decision ENUM('aprobada','aprobada_con_observaciones','rechazada','pendiente') NOT NULL DEFAULT 'pendiente',
  responsible_user_id VARCHAR(191) NOT NULL,
  released_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  conclusion TEXT NOT NULL,
  digital_confirmation VARCHAR(191) NOT NULL,
  document_ids_json JSON NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY lab_technical_releases_organization_id_idx (organization_id),
  KEY lab_technical_releases_sample_id_idx (sample_id),
  KEY lab_technical_releases_decision_idx (decision),
  CONSTRAINT lab_technical_releases_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT lab_technical_releases_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES lab_samples(id),
  CONSTRAINT lab_technical_releases_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE _LabReleaseTests (
  A VARCHAR(191) NOT NULL,
  B VARCHAR(191) NOT NULL,
  UNIQUE KEY _LabReleaseTests_AB_unique (A, B),
  KEY _LabReleaseTests_B_index (B),
  CONSTRAINT _LabReleaseTests_A_fkey FOREIGN KEY (A) REFERENCES lab_technical_releases(id) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT _LabReleaseTests_B_fkey FOREIGN KEY (B) REFERENCES lab_tests(id) ON DELETE CASCADE ON UPDATE CASCADE
);
