CREATE TABLE purchase_requests (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  origin VARCHAR(191) NOT NULL,
  requester_user_id VARCHAR(191) NOT NULL,
  area VARCHAR(191) NOT NULL,
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  required_date DATETIME(3) NULL,
  reason TEXT NOT NULL,
  status ENUM('borrador','enviada','en_revision','aprobada','rechazada','convertida','cancelada','cerrada') NOT NULL DEFAULT 'borrador',
  observations TEXT NULL,
  document_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY purchase_requests_permanent_code_key (permanent_code),
  KEY purchase_requests_organization_id_idx (organization_id),
  KEY purchase_requests_status_idx (status),
  CONSTRAINT purchase_requests_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_requests_requester_user_id_fkey FOREIGN KEY (requester_user_id) REFERENCES users(id),
  CONSTRAINT purchase_requests_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE purchase_request_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  request_id VARCHAR(191) NOT NULL,
  raw_material_master_id VARCHAR(191) NULL,
  commercial_product_id VARCHAR(191) NULL,
  item_name VARCHAR(191) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL,
  specifications TEXT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'activo',
  KEY purchase_request_items_organization_id_idx (organization_id),
  KEY purchase_request_items_request_id_idx (request_id),
  CONSTRAINT purchase_request_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_request_items_request_id_fkey FOREIGN KEY (request_id) REFERENCES purchase_requests(id)
);

CREATE TABLE purchase_requisitions (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  priority ENUM('baja','media','alta','urgente') NOT NULL DEFAULT 'media',
  target_date DATETIME(3) NULL,
  suggested_suppliers_json JSON NULL,
  estimated_budget DECIMAL(14,2) NULL,
  status ENUM('borrador','enviada','en_revision','aprobada','rechazada','convertida','cancelada','cerrada') NOT NULL DEFAULT 'en_revision',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY purchase_requisitions_permanent_code_key (permanent_code),
  KEY purchase_requisitions_organization_id_idx (organization_id),
  KEY purchase_requisitions_status_idx (status),
  CONSTRAINT purchase_requisitions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_requisitions_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE purchase_requisition_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  requisition_id VARCHAR(191) NOT NULL,
  request_item_id VARCHAR(191) NULL,
  item_name VARCHAR(191) NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL,
  target_date DATETIME(3) NULL,
  KEY purchase_requisition_items_organization_id_idx (organization_id),
  KEY purchase_requisition_items_requisition_id_idx (requisition_id),
  CONSTRAINT purchase_requisition_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_requisition_items_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES purchase_requisitions(id)
);

CREATE TABLE purchase_rfqs (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  requisition_id VARCHAR(191) NULL,
  supplier_names_json JSON NOT NULL,
  items_json JSON NOT NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  delivery_terms VARCHAR(191) NULL,
  deadline DATETIME(3) NULL,
  terms TEXT NULL,
  observations TEXT NULL,
  document_id VARCHAR(191) NULL,
  status ENUM('borrador','enviada','respondida_parcialmente','respondida','vencida','cancelada','cerrada') NOT NULL DEFAULT 'borrador',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY purchase_rfqs_permanent_code_key (permanent_code),
  KEY purchase_rfqs_organization_id_idx (organization_id),
  KEY purchase_rfqs_status_idx (status),
  CONSTRAINT purchase_rfqs_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_rfqs_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES purchase_requisitions(id),
  CONSTRAINT purchase_rfqs_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE purchase_quotes (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  rfq_id VARCHAR(191) NULL,
  supplier_id VARCHAR(191) NULL,
  supplier_name VARCHAR(191) NOT NULL,
  commercial_product_id VARCHAR(191) NULL,
  manufacturer_name VARCHAR(191) NULL,
  presentation VARCHAR(191) NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit_price DECIMAL(14,4) NOT NULL,
  tax_rate DECIMAL(8,4) NULL,
  shipping_cost DECIMAL(14,2) NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  exchange_rate DECIMAL(12,4) NULL,
  minimum_purchase DECIMAL(12,3) NULL,
  valid_until DATETIME(3) NULL,
  lead_time_days INT NULL,
  payment_terms VARCHAR(191) NULL,
  availability VARCHAR(191) NULL,
  document_id VARCHAR(191) NULL,
  observations TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY purchase_quotes_permanent_code_key (permanent_code),
  KEY purchase_quotes_organization_id_idx (organization_id),
  KEY purchase_quotes_supplier_name_idx (supplier_name),
  CONSTRAINT purchase_quotes_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_quotes_rfq_id_fkey FOREIGN KEY (rfq_id) REFERENCES purchase_rfqs(id),
  CONSTRAINT purchase_quotes_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE purchase_comparisons (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  quote_id VARCHAR(191) NOT NULL,
  criteria_json JSON NOT NULL,
  normalized_cost DECIMAL(14,4) NOT NULL,
  total_acquisition_cost DECIMAL(14,2) NOT NULL,
  quality_score DECIMAL(8,2) NULL,
  selected BOOLEAN NOT NULL DEFAULT false,
  selection_reason TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY purchase_comparisons_permanent_code_key (permanent_code),
  KEY purchase_comparisons_organization_id_idx (organization_id),
  KEY purchase_comparisons_selected_idx (selected),
  CONSTRAINT purchase_comparisons_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_comparisons_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES purchase_quotes(id)
);

CREATE TABLE purchase_orders (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  supplier_name VARCHAR(191) NOT NULL,
  requisition_id VARCHAR(191) NULL,
  quote_id VARCHAR(191) NULL,
  currency VARCHAR(191) NOT NULL DEFAULT 'MXN',
  exchange_rate DECIMAL(12,4) NULL,
  subtotal DECIMAL(14,2) NOT NULL,
  tax_total DECIMAL(14,2) NOT NULL,
  shipping_total DECIMAL(14,2) NOT NULL,
  discount_total DECIMAL(14,2) NOT NULL DEFAULT 0,
  total DECIMAL(14,2) NOT NULL,
  terms TEXT NULL,
  promised_date DATETIME(3) NULL,
  status ENUM('borrador','pendiente_aprobacion','aprobada','enviada','confirmada','parcialmente_recibida','recibida','cerrada','cancelada') NOT NULL DEFAULT 'borrador',
  responsible_user_id VARCHAR(191) NOT NULL,
  document_id VARCHAR(191) NULL,
  close_justification TEXT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL,
  UNIQUE KEY purchase_orders_permanent_code_key (permanent_code),
  KEY purchase_orders_organization_id_idx (organization_id),
  KEY purchase_orders_status_idx (status),
  CONSTRAINT purchase_orders_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_orders_requisition_id_fkey FOREIGN KEY (requisition_id) REFERENCES purchase_requisitions(id),
  CONSTRAINT purchase_orders_quote_id_fkey FOREIGN KEY (quote_id) REFERENCES purchase_quotes(id),
  CONSTRAINT purchase_orders_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT purchase_orders_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE purchase_order_items (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NOT NULL,
  commercial_product_id VARCHAR(191) NULL,
  raw_material_master_id VARCHAR(191) NULL,
  item_name VARCHAR(191) NOT NULL,
  quantity_ordered DECIMAL(12,3) NOT NULL,
  quantity_received DECIMAL(12,3) NOT NULL DEFAULT 0,
  unit VARCHAR(191) NOT NULL,
  unit_price DECIMAL(14,4) NOT NULL,
  tax_rate DECIMAL(8,4) NULL,
  line_total DECIMAL(14,2) NOT NULL,
  KEY purchase_order_items_organization_id_idx (organization_id),
  KEY purchase_order_items_order_id_idx (order_id),
  CONSTRAINT purchase_order_items_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_order_items_order_id_fkey FOREIGN KEY (order_id) REFERENCES purchase_orders(id)
);

CREATE TABLE purchase_approvals (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NOT NULL,
  approver_user_id VARCHAR(191) NOT NULL,
  decision VARCHAR(191) NOT NULL,
  comment TEXT NULL,
  level INT NOT NULL DEFAULT 1,
  evidence_document_id VARCHAR(191) NULL,
  decided_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY purchase_approvals_organization_id_idx (organization_id),
  KEY purchase_approvals_order_id_idx (order_id),
  CONSTRAINT purchase_approvals_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_approvals_order_id_fkey FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
  CONSTRAINT purchase_approvals_approver_user_id_fkey FOREIGN KEY (approver_user_id) REFERENCES users(id)
);

CREATE TABLE purchase_receipts (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NOT NULL,
  order_item_id VARCHAR(191) NULL,
  expected_quantity DECIMAL(12,3) NOT NULL,
  received_quantity DECIMAL(12,3) NOT NULL,
  difference_quantity DECIMAL(12,3) NOT NULL,
  supplier_lot_code VARCHAR(191) NULL,
  received_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  remision VARCHAR(191) NULL,
  invoice VARCHAR(191) NULL,
  package_status VARCHAR(191) NULL,
  initial_status VARCHAR(191) NOT NULL DEFAULT 'cuarentena',
  observations TEXT NULL,
  document_id VARCHAR(191) NULL,
  inventory_lot_id VARCHAR(191) NULL,
  inventory_movement_id VARCHAR(191) NULL,
  quality_inspection_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY purchase_receipts_permanent_code_key (permanent_code),
  KEY purchase_receipts_organization_id_idx (organization_id),
  KEY purchase_receipts_order_id_idx (order_id),
  CONSTRAINT purchase_receipts_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_receipts_order_id_fkey FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
  CONSTRAINT purchase_receipts_order_item_id_fkey FOREIGN KEY (order_item_id) REFERENCES purchase_order_items(id),
  CONSTRAINT purchase_receipts_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT purchase_receipts_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id)
);

CREATE TABLE purchase_returns (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  order_id VARCHAR(191) NULL,
  lot_id VARCHAR(191) NULL,
  reason TEXT NOT NULL,
  quantity DECIMAL(12,3) NOT NULL,
  unit VARCHAR(191) NOT NULL,
  evidence_document_id VARCHAR(191) NULL,
  responsible_user_id VARCHAR(191) NOT NULL,
  disposition VARCHAR(191) NOT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'registrada',
  inventory_movement_id VARCHAR(191) NULL,
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY purchase_returns_permanent_code_key (permanent_code),
  KEY purchase_returns_organization_id_idx (organization_id),
  KEY purchase_returns_order_id_idx (order_id),
  CONSTRAINT purchase_returns_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT purchase_returns_order_id_fkey FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
  CONSTRAINT purchase_returns_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id),
  CONSTRAINT purchase_returns_evidence_document_id_fkey FOREIGN KEY (evidence_document_id) REFERENCES documents(id)
);

CREATE TABLE supplier_evaluations (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  permanent_code VARCHAR(191) NOT NULL,
  supplier_name VARCHAR(191) NOT NULL,
  lots_received INT NOT NULL DEFAULT 0,
  lots_approved INT NOT NULL DEFAULT 0,
  lots_rejected INT NOT NULL DEFAULT 0,
  incomplete_documents INT NOT NULL DEFAULT 0,
  incidents INT NOT NULL DEFAULT 0,
  response_time_days DECIMAL(8,2) NULL,
  price_variation DECIMAL(8,2) NULL,
  score DECIMAL(8,2) NOT NULL,
  trend VARCHAR(191) NOT NULL DEFAULT 'estable',
  responsible_user_id VARCHAR(191) NOT NULL,
  evaluated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE KEY supplier_evaluations_permanent_code_key (permanent_code),
  KEY supplier_evaluations_organization_id_idx (organization_id),
  KEY supplier_evaluations_supplier_name_idx (supplier_name),
  CONSTRAINT supplier_evaluations_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id),
  CONSTRAINT supplier_evaluations_responsible_user_id_fkey FOREIGN KEY (responsible_user_id) REFERENCES users(id)
);

CREATE TABLE supply_suggestions (
  id VARCHAR(191) NOT NULL PRIMARY KEY,
  organization_id VARCHAR(191) NOT NULL,
  raw_material_master_id VARCHAR(191) NULL,
  item_name VARCHAR(191) NOT NULL,
  available_quantity DECIMAL(12,3) NOT NULL,
  reserved_quantity DECIMAL(12,3) NOT NULL,
  reorder_point DECIMAL(12,3) NOT NULL,
  suggested_quantity DECIMAL(12,3) NOT NULL,
  reason TEXT NOT NULL,
  status VARCHAR(191) NOT NULL DEFAULT 'sugerida',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  KEY supply_suggestions_organization_id_idx (organization_id),
  CONSTRAINT supply_suggestions_organization_id_fkey FOREIGN KEY (organization_id) REFERENCES organizations(id)
);
